---
- name: "DR_1node_02_김포1_2_OS종료"
  hosts: all
  serial: 1
  gather_facts: false
  tasks:
    - name: 일시 생성
      set_fact:
        today: "{{ lookup('ansible.builtin.pipe', 'date +%y%m%d') }}"
      delegate_to: localhost
      run_once: true
      
    - name: 변수 파일 호출
      include_vars: ../vars/server_ordering_02.yml

    - name: 사전 접속 검증
      raw: hostname
      register: host_result
      ignore_errors: true
      ignore_unreachable: true

    - name: Active1 DB 호스트 정보
      debug: 
        msg:
        - "Active DB 정보"
        - "IP: {{ FIRST_ACTIVE_DB_IP }}"
        - "HOSTNAME: {{ fap.host_name }}"
      when: fap.host_ip == FIRST_ACTIVE_DB_IP | default('none')

    - name: Active2 DB 호스트 정보
      debug: 
        msg:
        - "Active2 DB 정보"
        - "IP: {{ SECOND_ACTIVE_DB_IP }}"
        - "HOSTNAME: {{ fap.host_name }}"
      when: fap.host_ip == SECOND_ACTIVE_DB_IP | default('none')

    - name: 서버 접속 확인
      wait_for:
        host: "{{ FIRST_ACTIVE_DB_IP }}"
        port: 22
        state: started
        timeout: 5
      register: wait_check1
      ignore_errors: true
      when: fap.host_ip == FIRST_ACTIVE_DB_IP
      delegate_to: localhost

    - name: 서버 접속 확인
      wait_for:
        host: "{{ SECOND_ACTIVE_DB_IP }}"
        port: 22
        state: started
        timeout: 5
      register: wait_check2
      ignore_errors: true
      when: fap.host_ip == SECOND_ACTIVE_DB_IP
      delegate_to: localhost
  
    - name: "Step 2 - 김포 중지 {{ fap.host_name }}"
      include_tasks: ../tasks/Step_2.yml
      when: 
        - fap.host_ip == FIRST_ACTIVE_DB_IP | default(omit) or fap.host_ip == SECOND_ACTIVE_DB_IP | default(omit)
        - wait_check1.failed | default(omit) == false or wait_check2.failed | default(omit) == false
        - host_result.rc | default(omit) == 0

    - debug:
        msg:
        - "[Step 2] 완료 - DR_1node_02_김포 #1 #2 OS종료"