---
- name: Git 동기화 결과를 메일로 전송
  hosts: all
  gather_facts: false
  ignore_errors: true

  vars_files:
    - "/fap/ansible/projects/플레이북_git_동기화/templates/vault_mail.yml"

  vars:
    mail_smtp_host: "smtp.gmail.com"
    mail_smtp_port: 587
    mail_from: "{{ vault_mail_smtp_username }}"
    # mail_to: "sg.jang@gmail.com" # 보낸 편지함에선 확인 가능
    mail_to: "sg.jang@rtnet.co.kr" # 받은 편지함에서 확인 가능

  tasks:
    - name: 스크립트 파일 실행(git 동기화)
      raw: sh /fap/ansible/projects/플레이북_git_동기화/templates/code_git_push.sh
      register: sh_test

    - name: 스크립트 실행 디버그
      debug:
        var: sh_test

    - name: 작업 결과 메일 전송
      community.general.mail:
        host: "{{ mail_smtp_host }}"
        port: "{{ mail_smtp_port }}"
        username: "{{ vault_mail_smtp_username }}"
        password: "{{ vault_mail_smtp_password }}"
        secure: starttls
        from: "{{ mail_from }}"
        to: "{{ mail_to }}"
        subject: "[Ansible] Git 동기화 결과 - {{ inventory_hostname }}"
        body: |
          [Ansible Git 동기화 결과]

          호스트:
            - {{ inventory_hostname }}

          실행 결과:
          {% if sh_test.rc == 0 %}
            - 성공
          {% else %}
            - 실패
          {% endif %}

          Return Code:
            - {{ sh_test.rc }}

          표준 출력(stdout):
            - {{ sh_test.stdout | default('출력 없음') }}

          표준 에러(stderr):
            - {{ sh_test.stderr | default('에러 없음') }}
      delegate_to: localhost