---
#  아래의 명령어는 신세계랑 테스트 할때 진행
#  SQL> shutdown immediate

# 로그 저장 디렉토리 생성
- name: 백업 디렉토리 생성
  file:
    path: "{{ BACKUP_DIR }}"
    state: directory
  delegate_to: localhost

# step2. 1작업
- name: "김포 DB 상태 확인 {{ fap.host_name }}"
  raw: su - "{{ item.oracle_user }}" -c "{{ status_sh }}"
  register: result_status
  loop: "{{ ORACLE }}"
  loop_control:
    label: "{{ item.oracle_sid }}"
  when: item.oracle_sid != ""  # ORACLE_SID가 정의된 경우에만 실행

- name: "김포 DB 중지 {{ fap.host_name }}"
  raw: su - "{{ item.item.oracle_user }}" -c "{{ shutdown_sh }}"
  register: result
  loop: "{{ result_status.results }}"
  loop_control:
    label: "{{ item.item.oracle_sid }}"
  when: 
    - item.item.oracle_sid != ""  # ORACLE_SID가 정의된 경우에만 실행
    - "'OPEN' in item.stdout_lines"

- name: 동기화 중지 명령어 결과 백업 ---> localhost
  blockinfile:
    path: "{{ BACKUP_DIR }}/{{ SHUTDOWN_IMMEDIATE_FILE }}"
    create: true
    block: |
      {{ item.stdout }}
    marker: "# {mark} 동기화 중지 명령어 결과 백업"
  loop: "{{ result.results }}"
  loop_control:
    label: "{{ item.item.item.oracle_sid }}"
  when: item.stdout is defined
  register: blockinfile_result
  delegate_to: localhost
  ignore_errors: yes

- name: 동기화 중지 명령어 결과 백업 경로 출력 ---> localhost
  when: blockinfile_result.changed | bool
  debug:
    msg: "저장 경로 : {{ BACKUP_DIR }}/{{ SHUTDOWN_IMMEDIATE_FILE }}"

# step2. 2작업
- name: 김포 CRS 중지
  raw: |
    source ~/.bash_profile
    crsctl disable crs
    crsctl stop crs
  args:
    executable: /bin/bash     
  register: result_stop_crs
  ignore_errors: yes

- name: 김포 CRS 중지 명령어 결과 백업 ---> localhost
  blockinfile:
    path: "{{ BACKUP_DIR }}/{{ STOP_CRS_FILE }}"
    create: true
    block: |
      {{ result_stop_crs.stdout | default(result_stop_crs.stderr, true) }}
    marker: "# {mark} 김포 CRS 중지 명령어 결과 백업"
  register: blockinfile_result_crs
  delegate_to: localhost

- name: 김포 CRS 중지 명령어 결과 백업 경로 출력 ---> localhost
  debug:
    msg: "{{ blockinfile_result_crs.diff[0].after_header }}"

# step2. cubeone 중지 필요 시 호출
- name: cubeone 작업 실행
  include_tasks: ../tasks/cubeone_task.yml
  when: CUBEONE_WORK in ['y','Y']

# step2. 4작업
- name: 김포 OS sync 명령어 수행
  raw: sync;sync;sync;

- name: 김포 OS 중지
  raw: /sbin/shutdown -h now
  register: shutdown_result
  ignore_unreachable: true
  ignore_errors: true
  failed_when: false

# - name: 김포 OS 중지
#   community.general.shutdown:
#   register: result_shutdown