---
- name: first_ip 전용 작업 실행 여부 설정
  set_fact:
    is_first_ip_target: "{{ (fap.host_ip | default(inventory_hostname) | string) == (first_ip | string) }}"

- name: 서버 현황
  include_tasks: "../tasks/version_check.yml"

- name: 1. CPU, 디스크, 메모리 사용률 점검
  include_tasks: "../tasks/1_cpu_disck_mem_check.yml"

- name: 2. 패치 관리 항목 점검 # common 함수에 내용 직접 작성
  include_tasks: "../tasks/2_patch_check.yml"

- name: 3. 자동화 서버 관련 프로세스 가동 점검
  include_tasks: "../tasks/3_server_docker_check.yml"

- name: 4. 자동화 서버 웹 UI 서비스 상태 점검 # first_ip 에서만 실행
  include_tasks: "../tasks/4_ui_service_check.yml"
  when: is_first_ip_target | bool

- name: 5. 사용자 계정 현황 점검 # first_ip 에서만 실행
  include_tasks: "../tasks/5_ui_user_check.yml"
  when: is_first_ip_target | bool

- name: 6. 자동화 템플릿 점검 # 작업 템플릿 당월/전월 생성 수 비교 # first_ip 에서만 실행
  include_tasks: "../tasks/6_template_check.yml"
  when: is_first_ip_target | bool

- name: 7. 웹 접속 IP 점검 # first_ip 에서만 실행
  include_tasks: "../tasks/7_ui_web_ip_check.yml"
  when: is_first_ip_target | bool

- name: 8. DR 워크플로우 점검 # first_ip 에서만 실행
  include_tasks: "../tasks/8_dr_workflow_check.yml"
  when: is_first_ip_target | bool

- name: 9. 작업 관리 # common 함수에 내용 직접 작성
  include_tasks: "../tasks/9_man_month_check.yml"

- name: 10. DR 모의훈련 작업 내역 # first_ip 에서만 실행
  include_tasks: "../tasks/10_dr_mock_training_check.yml"
  when: is_first_ip_target | bool
