---
- name: 서버파트_FALCON_정기점검_문서생성
  hosts: all
  ignore_errors: false
  ignore_unreachable: false
  gather_facts: false
  vars: # 보고서에 들어갈 내용 변수값 (변수명의 경우 대문자)
    FIRST_IP: "172.20.1.173" # 작업 결과 윗줄에 들어갈 대상 IP
    SECOND_IP: "192.168.1.202" # 작업 결과 아랫줄에 들어갈 대상 IP
    FIRST_NAME: "장상기" # 알티넷 담당자명
    SECOND_NAME: "박소은" # 신세계 아이앤씨 담당자명
    SPECIAL_NOTE: "특이사항 없음" # 특이사항 입력 부분 작성 내용
  vars_files:
    - "../vars/common.yml"
  pre_tasks:
    - name: 연결 상태 확인
      include_tasks: "../tasks/con_check.yml"
      register: con_check

  tasks:
    - name: 점검 실행
      include_tasks: "../tasks/server_periodic_check.yml"
      register: check_task
      when: con_check.stdout is defined

    - name: save to DB
      include_tasks: "../tasks/save_to_db.yml"

    - name: 보고서 생성
      include_tasks: "../tasks/make_report.yml"
      when:
        - con_check.stdout is defined
        - (fap.host_ip | default(inventory_hostname) | string) == (first_ip | string)

    # - name: 플레이북 백업
    #   raw: |
    #     cd /app/fap/ansible
    #     sh exec_backup_projects.sh
    #   register: projects_backup
    #   delegate_to: localhost
