---
- name: DR_Manual_2
  hosts: all
  gather_facts: false
  tasks:
  - name: 일시 생성
    set_fact:
      today: "{{ lookup('ansible.builtin.pipe', 'date +%y%m%d') }}"
    delegate_to: localhost
    run_once: true

  - name: 변수 파일 호출
    include_vars: ../vars/DR_Manual_vars02.yml

  - name: Standy DB의 호스트 정보
    debug: 
      msg:
      - "IP: {{ STANDBY_DB_IP }}"
      - "HOSTNAME: {{ fap.host_name }}"
    when: fap.host_ip == STANDBY_DB_IP | default('none')
    
  - name: IP 기동
    raw: "/sbin/ifconfig {{ item.eth }} {{ item.ip }}/24 up"
    loop: "{{ DR_DB_IP_EXE_LIST }}"
    register: DR_DB_IP_EXE_RESULT
    when: item.eth != ""
    
  - name: 통신 확인
    wait_for:
      host: "{{ item.ip }}"
      port: 22
      state: started
      timeout: 3600
    loop: "{{ DR_DB_IP_EXE_LIST }}"
    loop_control:
      label: "{{ item.ip }}"
    when: item.eth != ""
    delegate_to: localhost
    
  - name: IP 기동 결과 확인
    raw: /sbin/ifconfig -a
    register: ifconfig_result
    
  - name: IP 기동 결과 출력
    debug:
      msg: "{{ ifconfig_result.stdout }}"
