---
- name: Git 동기화 결과를 메일로 전송
  hosts: all
  gather_facts: false

  vars_files:
    - "../vars/common.yml" # 공통변수
    - "/fap/ansible/projects/플레이북_git_동기화/templates/vault_mail.yml"

  # pre_tasks:
  #   - name: branch 사전 작업
  #     include_tasks: "../tasks/branch_check.yml"

  tasks:
    - name: Git 저장소 Clone 또는 Pull 수행
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ git_dest_path }}"
        version: main
        update: true
        accept_hostkey: true
      environment:
        GIT_SSH_COMMAND: >-
          ssh
          -i {{ git_ssh_key_path }}
          -o IdentitiesOnly=yes
          -o StrictHostKeyChecking=accept-new
      register: git_result
      delegate_to: localhost

    - name: 스크립트 파일 실행
      command:
        argv:
          - sh
          - "{{ git_sync_script_path }}"
      register: sh_test
      changed_when: true
      delegate_to: localhost
      ignore_errors: true
      environment:
        GIT_SSH_COMMAND: >-
          ssh
          -i {{ git_ssh_key_path }}
          -o IdentitiesOnly=yes
          -o StrictHostKeyChecking=accept-new

    - name: 작업 결과 메일 전송
      include_tasks: "../tasks/send_mail.yml"